# Generated by Django 6.1.1 on 2026-09-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_focussession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedwebsite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_websites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockedwebsite',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='blockedwebsite',
            unique_together={('user', 'domain')},
        ),
    ]
